.pragma library

// The door's palette: gold on black. Deliberately its own.
//
// The four tables the desktop inside can wear (house/Config.qml) are rooms you
// choose; this is the room you walk through to reach them, and it does not
// change. Nothing here is generated by apply-theme.sh: the greeter runs as the
// `sddm` user before any login, with no access to anyone's ~/.config, and a
// login screen that quietly followed a per-user preference would be a login
// screen announcing which user last sat down.
//
// Black lacquer and gold, lit from directly above, and almost nothing else. The
// restraint is the point: with the room reduced to two colours, the clay chips
// are the only real colour on the screen, so the bet is the thing your eye goes
// to - which is exactly where it should go, because the bet is the password.
//
// A .js library rather than a QML singleton, which is the obvious way to write
// this and does not work here. A `singleton` line in a qmldir is only honoured
// when the directory is imported as a module; an SDDM theme is a bare directory
// of files that Qt imports implicitly, so the qmldir is never consulted and
// every `Palette.x` silently resolves to undefined - which raises no error, it
// just leaves every Rectangle at its default white and every Text at its
// default black. A .pragma library is read the same way from anywhere and has
// no such trapdoor.

// --- the room -----------------------------------------------------------------
// tableDeep is the cloth away from the lamp; tableLit is what the cone lands on
// - not a lighter black but a warmer one, because the light in here is gold and
// a gold lamp over black lacquer warms it rather than greying it. Felt.qml
// gradients between the two, so the background is never a flat rectangle.
var tableDeep = "#0a0908";
var tableLit = "#241d13";
var tableLine = "#3a2f18"; // the lattice printed on the cloth, barely there

var rail = "#141110"; // lacquer, the padded edge you lean on
var railLit = "#2a2320";
var railShadow = "#040303";

// --- the fittings -------------------------------------------------------------
var gold = "#d9a92e";
var goldDim = "#8a6d1e"; // hairlines, inactive plaques
var goldBright = "#f4dd97"; // the lit edge of a bevel

// --- card stock ---------------------------------------------------------------
var ivory = "#f2ead6";
var ivoryDim = "#cfc7b4";
var cardInk = "#14100f";
var cardRed = "#b3241f";
var cardBack = "#171310"; // black, gold-latticed
var cardBackLine = "#6b5320";

// --- type ---------------------------------------------------------------------
var text = "#f2ead6";
var muted = "#8d8375"; // warm grey, never a neutral one
var hot = "#cf3b32"; // caps lock, bust, swept

// --- the chips ----------------------------------------------------------------
// House colours only - ivory, red, black, gold - so every chip belongs to the
// same room. The green and purple of a real rack are the right colours in a
// real casino and the wrong ones here; they would be the only two things on
// screen that came from somewhere else.
//
// The bet climbs through these as it grows, so the colour of the top chip says
// roughly how long the password is without anyone counting chips.
//
// Each: the clay body, the contrasting inlay let into the edge spots, and an
// ink that reads on the body.
var chips = [
    {
        body: "#ece4d0",
        spot: "#14100f",
        ink: "#14100f",
        value: "1"
    },      // ivory, black spots
    {
        body: "#b3282a",
        spot: "#ece4d0",
        ink: "#f7ece9",
        value: "5"
    },      // red, ivory spots
    {
        body: "#131110",
        spot: "#d9a92e",
        ink: "#e8d5a0",
        value: "100"
    },    // black, gold spots
    {
        body: "#d9a92e",
        spot: "#14100f",
        ink: "#2a2010",
        value: "500"
    }     // gold, black spots
];

// The power chips on the rail wear house colours rather than a denomination -
// they are not part of the bet, and a gold 500 that shuts the machine down is a
// button somebody clicks while looking at the stack they are building.
var powerChip = {
    body: "#251e17",
    spot: "#6b5320",
    ink: "#d9a92e"
};

var powerChipHot = {
    body: "#3d1512",
    spot: "#cf3b32",
    ink: "#f4d8d4"
};

// alpha("#rrggbb", 0.55) -> "#8crrggbb", a form Qt parses directly.
//
// Here rather than at each call site because the alternative - Qt.rgba() on the
// unpacked channels of a colour - needs a QML context this library does not
// have, and spelling it out inline is four property reads per use.
function alpha(hex, a) {
    var v = Math.round(Math.max(0, Math.min(1, a)) * 255);
    var h = v.toString(16);
    if (h.length < 2)
        h = "0" + h;
    return "#" + h + hex.substring(1);
}
