pragma Singleton

import QtQuick

// The door's palette. Deliberately its own.
//
// The four tables inside (house/Config.qml) are rooms you choose; this is the
// room you walk through to get to them, and it does not change. So none of the
// six roles are imported and nothing here is generated by apply-theme.sh - the
// greeter runs as the `sddm` user before any login, with no access to a user's
// ~/.config, and a login screen that quietly follows a per-user preference is a
// login screen that leaks which user last sat down.
//
// One high-limit pit, lit from directly above: emerald baize, a mahogany rail,
// brass fittings, ivory card stock, and the clay-chip denominations doing the
// actual colour work.
QtObject {
    // --- the room -------------------------------------------------------------
    // feltDeep is the cloth away from the lamp; feltLit is what the cone lands
    // on. Felt.qml gradients between them, so neither is a flat backdrop.
    readonly property color feltDeep: "#071710"
    readonly property color feltLit: "#123d27"
    readonly property color feltLine: "#1d5638" // the lattice printed on the cloth

    readonly property color rail: "#3b2416" // mahogany, the padded edge you lean on
    readonly property color railLit: "#5a3a22"
    readonly property color railShadow: "#1b0f08"

    // --- the fittings ---------------------------------------------------------
    readonly property color brass: "#c8a02e"
    readonly property color brassDim: "#7d631d" // hairlines, inactive plaques
    readonly property color brassBright: "#f0d68a" // the lit edge of a bevel

    // --- card stock -----------------------------------------------------------
    readonly property color ivory: "#f4efe2"
    readonly property color ivoryDim: "#cfc7b4" // the face of a card out of the light
    readonly property color cardInk: "#14100f"
    readonly property color cardRed: "#b3241f"
    readonly property color cardBack: "#5c1d22" // burgundy, brass-latticed
    readonly property color cardBackLine: "#8c3a34"

    // --- type -----------------------------------------------------------------
    readonly property color text: "#f4efe2"
    readonly property color muted: "#8fa798" // cloth-side grey-green, not neutral grey
    readonly property color hot: "#d8463c" // caps lock, denied, swept

    // --- the chips ------------------------------------------------------------
    // Real clay denominations, in the order a rack is filled. The stack cycles
    // through these as it grows, so a long password climbs through the colours
    // the way a real bet does - and the top chip is always the biggest one you
    // have put in.
    //
    // Each: the clay body, the contrasting inlay on the edge spots, and the ink
    // that reads on the body.
    readonly property var chips: [
        {
            body: "#f2f0eb",
            spot: "#2f6db5",
            ink: "#1a1a1a",
            value: "1"
        }, // white
        {
            body: "#c0392f",
            spot: "#f2f0eb",
            ink: "#f7ece9",
            value: "5"
        }, // red
        {
            body: "#1e7a4a",
            spot: "#f2f0eb",
            ink: "#eaf6ee",
            value: "25"
        }, // green
        {
            body: "#14100f",
            spot: "#c8a02e",
            ink: "#e8dcbc",
            value: "100"
        }, // black
        {
            body: "#6b3fa0",
            spot: "#f2f0eb",
            ink: "#efe7f7",
            value: "500"
        }  // purple
    ]

    // The power chips on the rail wear their own colours - they are not part of
    // the bet, so they must not read as denominations.
    readonly property var powerChip: ({
            body: "#2a1a12",
            spot: "#7d631d",
            ink: "#c8a02e"
        })
    readonly property var powerChipHot: ({
            body: "#5a1a16",
            spot: "#d8463c",
            ink: "#f4d8d4"
        })
}
