.pragma library

// The door's palette: gold on black. Deliberately its own.
//
// The four tables the desktop inside can wear (house/Config.qml) are rooms you
// choose; this is the room you walk through to reach them, and it does not
// change. Nothing here is generated by apply-theme.sh: the greeter runs as the
// `sddm` user before any login, with no access to anyone's ~/.config, and a
// login screen that quietly followed a per-user preference would be a login
// screen announcing which user last sat down.
//
// Black lacquer and gold, lit from directly above, and almost nothing else. The
// restraint is the point: with the room reduced to two colours, the clay chips
// are the only real colour on the screen, so the bet is the thing your eye goes
// to - which is exactly where it should go, because the bet is the password.
//
// A .js library rather than a QML singleton, which is the obvious way to write
// this and does not work here: a `singleton` line in a qmldir is only honoured
// when the directory is imported as a module, and an SDDM theme is a bare
// directory Qt imports implicitly. The qmldir is never consulted, so every
// `Palette.x` resolves to undefined with no error at all - just white Rectangles
// and black Text. A .pragma library reads the same from anywhere.

// --- the room -----------------------------------------------------------------
// tableDeep is the cloth away from the lamp; tableLit is what the cone lands on
// - not a lighter black but a warmer one, because the light in here is gold and
// a gold lamp over black lacquer warms it rather than greying it. Felt.qml
// gradients between the two, so the background is never a flat rectangle.
var tableDeep = "#0a0908";
var tableLit = "#241d13";
var tableLine = "#3a2f18"; // the lattice printed on the cloth, barely there

var rail = "#141110"; // lacquer, the padded edge you lean on
var railLit = "#2a2320";
var railShadow = "#040303";

// --- the fittings -------------------------------------------------------------
var gold = "#d9a92e";
var goldDim = "#8a6d1e"; // hairlines, inactive plaques
var goldBright = "#f4dd97"; // the lit edge of a bevel

// --- card stock ---------------------------------------------------------------
var ivory = "#f2ead6";
var ivoryDim = "#cfc7b4";
var cardInk = "#14100f";
var cardRed = "#b3241f";
var cardBack = "#171310"; // black, gold-latticed
var cardBackLine = "#6b5320";

// --- type ---------------------------------------------------------------------
var text = "#f2ead6";
var muted = "#8d8375"; // warm grey, never a neutral one
var hot = "#cf3b32"; // caps lock, bust, swept

// --- the chips ----------------------------------------------------------------
// Red, black, blue, purple - four denominations, one per stack of the bet.
//
// Deliberately none of the room's own colours. An earlier set ran ivory, red,
// black, gold - the room in miniature, and the problem: the gold chip was the
// colour of the plaques it sat among, and the ivory chip the colour of the type.
// The chips are the one thing here that is not lacquer and gold. Black stays,
// because a rack without it does not look like a rack, and it earns its place by
// being darker than the cloth rather than lighter.
//
// The bet climbs through these as it grows, three chips to a colour, so the clay
// at the top says roughly how long the password is. Three and not one: a single
// chip of each colour is a stripe, where three is a band you can see.
//
// Each: the clay body, the contrasting inlay let into the edge spots, and an
// ink that reads on the body.
var chips = [
    {
        body: "#b3282a",
        spot: "#ece4d0",
        ink: "#f7ece9",
        value: "5"
    },      // red, ivory spots
    {
        body: "#131110",
        spot: "#ffffff",
        ink: "#ffffff",
        value: "25"
    },     // black, white spots. Flat white rather than ivory: this is the only
           // chip darker than the cloth, so its spots do the whole job of
           // separating it from the felt, and ivory is not a big enough step
           // off near-black at the size a rim spot gets drawn.
    {
        body: "#22508a",
        spot: "#ece4d0",
        ink: "#dce6f2",
        value: "100"
    },    // blue, ivory spots
    {
        body: "#6a3287",
        spot: "#ece4d0",
        ink: "#ecdcf4",
        value: "500"
    }     // purple, ivory spots
];

// --- court stock --------------------------------------------------------------
// The seat cards are printed in the room's own three colours rather than on
// ivory: black stock, gold rule, white figures. A seat card is a piece of this
// room and not a card out of the shoe - the shoe's are the pale ones - so the
// two never get confused even when the showdown lands on top of the fan.
//
// Flat white for the figures: ivory reads as warm at nameplate size, but at a
// hairline it just reads as a slightly dirty white.
var courtStock = "#171310";
var courtFigure = "#ffffff";

// The power chips on the rail wear house colours rather than a denomination -
// they are not part of the bet, and a gold 500 that shuts the machine down is a
// button somebody clicks while looking at the stack they are building.
var powerChip = {
    body: "#251e17",
    spot: "#6b5320",
    ink: "#d9a92e"
};

var powerChipHot = {
    body: "#3d1512",
    spot: "#cf3b32",
    ink: "#f4d8d4"
};

// alpha("#rrggbb", 0.55) -> "#8crrggbb", a form Qt parses directly.
//
// Here rather than at each call site because the alternative - Qt.rgba() on the
// unpacked channels of a colour - needs a QML context this library does not
// have, and spelling it out inline is four property reads per use.
function alpha(hex, a) {
    var v = Math.round(Math.max(0, Math.min(1, a)) * 255);
    var h = v.toString(16);
    if (h.length < 2)
        h = "0" + h;
    return "#" + h + hex.substring(1);
}
