-- AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh — do not edit by hand.
-- Rewritten whenever a table is chosen in the house bar's picker; required from
-- hyprland.lua so the choice sticks across a restart. The returned palette is
-- there for reuse (local house = require("colors")); hl.config below is what paints.

hl.config({
    -- The rail. Flat accent on every table but vegas, which keeps the gradient.
    general = {
        border_size = 2,
        col = {
            active_border   = "rgba(d4af5fee)",
            inactive_border = "rgba(2a232055)",
        },
    },

    -- The spotlight.
    decoration = {
        dim_strength = 0.25,
        shadow = {
            color          = "rgba(d4af5f33)",
            color_inactive = "rgba(00000088)",
        },
    },
})

return {
    surface = "rgb(0e0b0d)",
    text    = "rgb(e8ddc4)",
    subtext = "rgb(8a7f6d)",
    accent  = "rgb(d4af5f)",
    idle    = "rgb(2a2320)",
    urgent  = "rgb(c13a4e)",
}
