-- AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh -- do not edit by hand.
-- Rewritten whenever a table is chosen in the house bar's picker; required from
-- hyprland.lua so the choice sticks across a restart. The returned table is
-- here for reuse (e.g. from binds or window rules); the hl.config() call below
-- is what paints.

local M = {}

M.surface = "rgb(0e0b0d)"
M.text    = "rgb(e8ddc4)"
M.subtext = "rgb(8a7f6d)"
M.accent  = "rgb(d4af5f)"
M.idle    = "rgb(2a2320)"
M.urgent  = "rgb(c13a4e)"

hl.config({
    general = {
        -- The rail. Flat accent on every table but vegas, which keeps the gradient.
        border_size = 2,
        col = {
            active_border   = "rgba(d4af5fee)",
            inactive_border = "rgba(2a232055)",
        },
    },

    decoration = {
        -- The spotlight.
        dim_strength = 0.25,
        shadow = {
            color          = "rgba(d4af5f33)",
            color_inactive = "rgba(00000088)",
        },
    },
})

return M
