-- Generated by nwg-displays on 2026-06-11 at 04:40:37. Do not edit manually.

hl.monitor({
    output = "HDMI-A-2",
    mode = "1600x900@59.98",
    position = "2560x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-4",
    mode = "2560x1440@120.0",
    position = "0x0",
    scale = 1.0
})
