-- Generated by nwg-displays on 2026-06-10 at 22:11:53. Do not edit manually.
--
-- MIGRATION NOTE (remove once confirmed on the real machine): the .lua file
-- nwg-displays left behind disagreed with workspaces.conf -- it put 6-10 on
-- HDMI-A-2 and dropped `default`/`persistent` from 1 and 6. The .conf values
-- are what is reproduced here, because that is the file that was actually
-- driving the desktop. If the second head really is HDMI-A-2, re-run
-- nwg-displays rather than hand-editing.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-4",
    default = true,
    persistent = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-4"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-4"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-4"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-4"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
    default = true,
    persistent = true
})
hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-1"
})
