#!/bin/sh
# apply-theme.sh — mirror the house bar's active theme onto Hyprland.
#
# The theme picker (Config.setTheme in the house shell) calls this with the six
# role colours of the chosen theme. It writes ~/.config/hypr/colors.conf — sourced
# from hyprland.conf so the choice survives a restart — and, if Hyprland is up,
# applies the same values live through hyprctl so the window borders retint
# without a reload.
#
# It is the single place system-wide theming is spelled out: to also drive, say,
# hyprlock or kitty, add another block here rather than teaching the shell about
# each app.
#
# Args, in Config.themes order: surface text subtext accent idle urgent
# Each is a "#rrggbb" hex string; the leading # is optional.

set -eu

if [ "$#" -lt 6 ]; then
    echo "usage: $0 surface text subtext accent idle urgent" >&2
    exit 2
fi

# Strip a leading '#', if any, so the values slot straight into rgb()/rgba().
surface=${1#\#}
text=${2#\#}
subtext=${3#\#}
accent=${4#\#}
idle=${5#\#}
urgent=${6#\#}

conf="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/colors.conf"

# Hyprland wants rgba(rrggbbaa). The focused window's border takes the accent, to
# match the bar; the inactive border stays transparent (themed but invisible, as
# the shipped config had it); the shadow is the surface, dimmed.
active="rgba(${accent}ee)"
inactive="rgba(${idle}00)"
shadow="rgba(${surface}ee)"

cat > "$conf" <<EOF
# AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh — do not edit by hand.
# Rewritten whenever a theme is chosen in the house bar's picker; sourced from
# hyprland.conf so the choice sticks across a restart. The \$-variables are here
# for reuse (e.g. from binds or window rules); the keywords below are what paint.

\$surface = rgb($surface)
\$text    = rgb($text)
\$subtext = rgb($subtext)
\$accent  = rgb($accent)
\$idle    = rgb($idle)
\$urgent  = rgb($urgent)

general:col.active_border = $active
general:col.inactive_border = $inactive
decoration:shadow:color = $shadow
EOF

# Apply live if there's a compositor to talk to. Without one (script run outside a
# session, or Hyprland not up yet) the sourced file covers the next startup.
#
# `keyword` alone updates the stored value but doesn't redraw borders already on
# screen until the window is refocused - so a theme switch wouldn't visibly land.
# A reload re-sources hyprland.conf (hence colors.conf, just written above) and
# repaints every border; it does not re-run exec-once, so it's cheap and safe.
if command -v hyprctl >/dev/null 2>&1 && hyprctl version >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
fi
