#!/bin/sh
# apply-theme.sh — mirror the house bar's active table onto the rest of the
# desktop: Hyprland borders, the wallpaper, kitty, rofi, btop and starship.
#
# The theme picker (Config.setTheme in the house shell) calls this with the
# table's name and its six role colours. It is the single place system-wide
# theming is spelled out: to also drive another app, add a block here rather
# than teaching the shell about it.
#
# Args, in Config.themes order: name surface text subtext accent idle urgent
# Colours are "#rrggbb" hex strings; the leading # is optional.
#
# Per-table palettes that need more than the six roles (kitty's 16-colour deck,
# starship's segments) live pre-baked in tables/ next to this script; things the
# six roles can express (hypr, rofi) are generated right here.

set -eu

if [ "$#" -lt 7 ]; then
    echo "usage: $0 name surface text subtext accent idle urgent" >&2
    exit 2
fi

name=$1

# Strip a leading '#', if any, so the values slot straight into rgb()/rgba().
surface=${2#\#}
text=${3#\#}
subtext=${4#\#}
accent=${5#\#}
idle=${6#\#}
urgent=${7#\#}

here=$(dirname "$(readlink -f "$0")")
tables="$here/tables"
repo=$(readlink -f "$here/../..")
config="${XDG_CONFIG_HOME:-$HOME/.config}"

# --- Hyprland -----------------------------------------------------------------
# The focused window's border takes the accent, to match the bar; the inactive
# border stays transparent (themed but invisible); the shadow is the surface,
# dimmed. Written to colors.conf, sourced last from hyprland.conf.

cat > "$config/hypr/colors.conf" <<EOF
# AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh — do not edit by hand.
# Rewritten whenever a table is chosen in the house bar's picker; sourced from
# hyprland.conf so the choice sticks across a restart. The \$-variables are here
# for reuse (e.g. from binds or window rules); the keywords below are what paint.

\$surface = rgb($surface)
\$text    = rgb($text)
\$subtext = rgb($subtext)
\$accent  = rgb($accent)
\$idle    = rgb($idle)
\$urgent  = rgb($urgent)

general:col.active_border = rgba(${accent}ee)
general:col.inactive_border = rgba(${idle}00)
decoration:shadow:color = rgba(${surface}ee)
EOF

# --- Wallpaper ----------------------------------------------------------------
# One generated wallpaper per table, shipped in the repo. awww is the daemon the
# hypr config autostarts; fall back to swww for setups that use that instead.

wall="$repo/wallpapers/$name.png"
if [ -f "$wall" ]; then
    if command -v awww >/dev/null 2>&1; then
        awww img "$wall" >/dev/null 2>&1 || true
    elif command -v swww >/dev/null 2>&1; then
        swww img "$wall" >/dev/null 2>&1 || true
    fi
fi

# --- kitty --------------------------------------------------------------------
# The 16-colour deck can't be derived from six roles, so each table ships a
# pre-baked palette. kitty.conf includes current-table.conf; SIGUSR1 makes every
# running kitty re-read its config, so open terminals retint immediately.

if [ -f "$tables/kitty-$name.conf" ]; then
    cp "$tables/kitty-$name.conf" "$config/kitty/current-table.conf"
    pkill -USR1 -x kitty 2>/dev/null || true
fi

# --- rofi ---------------------------------------------------------------------
# house.rasi imports table-colours.rasi for its palette; everything rofi needs
# fits in the six roles, so generate it. rofi starts fresh per launch, so the
# next Super+D is already on the new table.

cat > "$config/rofi/themes/table-colours.rasi" <<EOF
/* AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh — do not edit.
 * The active table's palette, imported by house.rasi. */
* {
    surface:                 #${surface}E6;
    lacquer:                 #${idle};
    gold:                    #${accent};
    ivory:                   #${text};
    smoke:                   #${subtext};
    crimson:                 #${urgent};
    onaccent:                #${surface};
}
EOF

# --- btop ---------------------------------------------------------------------
# One pre-baked .theme per table (they ship in the btop stow package). Running
# btop instances pick it up on restart.

if [ -f "$config/btop/themes/house-$name.theme" ]; then
    sed -i "s/^color_theme = .*/color_theme = \"house-$name\"/" "$config/btop/btop.conf" 2>/dev/null || true
fi

# --- starship -----------------------------------------------------------------
# Same story as kitty: segment palettes are pre-baked per table. starship
# re-reads its config every prompt, so the very next Enter is on the new table.

if [ -f "$tables/starship-$name.toml" ]; then
    cp "$tables/starship-$name.toml" "$config/starship.toml"
fi

# --- Hyprland, live -----------------------------------------------------------
# `keyword` alone updates the stored value but doesn't redraw borders already on
# screen until the window is refocused - so a theme switch wouldn't visibly land.
# A reload re-sources hyprland.conf (hence colors.conf, just written above) and
# repaints every border; it does not re-run exec-once, so it's cheap and safe.
if command -v hyprctl >/dev/null 2>&1 && hyprctl version >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
fi
