#!/bin/sh
# apply-theme.sh — mirror the house bar's active table onto the rest of the
# desktop: Hyprland borders, the wallpaper, kitty, rofi, btop and starship.
#
# The theme picker (Config.setTheme in the house shell) calls this with the
# table's name and its six role colours. It is the single place system-wide
# theming is spelled out: to also drive another app, add a block here rather
# than teaching the shell about it.
#
# Args, in Config.themes order: name surface text subtext accent idle urgent
# Colours are "#rrggbb" hex strings; the leading # is optional.
#
# Per-table palettes that need more than the six roles (kitty's 16-colour deck,
# starship's segments) live pre-baked in tables/ next to this script; things the
# six roles can express (hypr, rofi) are generated right here.

set -eu

if [ "$#" -lt 7 ]; then
    echo "usage: $0 name surface text subtext accent idle urgent" >&2
    exit 2
fi

name=$1

# Strip a leading '#', if any, so the values slot straight into rgb()/rgba().
surface=${2#\#}
text=${3#\#}
subtext=${4#\#}
accent=${5#\#}
idle=${6#\#}
urgent=${7#\#}

here=$(dirname "$(readlink -f "$0")")
tables="$here/tables"
repo=$(readlink -f "$here/../..")
config="${XDG_CONFIG_HOME:-$HOME/.config}"

# --- colour helpers -----------------------------------------------------------
# Up here rather than beside the first block that happens to use them: Hyprland
# is generated first and needs mix() for the middle stop of the border gradient.

# dec RRGGBB -> "r, g, b", for the decimal rgba() hyprlock wants.
dec() {
    awk -v h="$1" 'BEGIN {
        printf "%d, %d, %d", strtonum("0x" substr(h,1,2)), strtonum("0x" substr(h,3,2)), strtonum("0x" substr(h,5,2));
    }'
}

# mix AABBCC DDEEFF t -> the two colours blended, t from first (0) to second (1).
mix() {
    awk -v a="$1" -v b="$2" -v t="$3" 'BEGIN {
        for (i = 0; i < 3; i++) {
            x = strtonum("0x" substr(a, 1 + i * 2, 2));
            y = strtonum("0x" substr(b, 1 + i * 2, 2));
            printf "%02x", int(x + (y - x) * t + 0.5);
        }
    }'
}

# --- Hyprland -----------------------------------------------------------------
# The whole window style, not just the border colour: the rail (the line round
# the focused window) and the spotlight (how hard everything else is dimmed, and
# what colour the glow over the live one is). hyprland.conf holds the geometry
# and the motion; everything with a colour in it is here, so switching tables
# restyles the windows and not just the bar.
#
# Most of it falls out of the six roles. The exceptions get a case below, the
# same way kitty's 16-colour deck and starship's segments are pre-baked: the
# rail wants a third stop the roles do not name, and the dim wants a different
# weight on a light table, where 0.25 reads as muddy rather than as unlit.

# The default rail is a flat line of the accent, kept thin. The highlight on the
# focused window is meant to come from the glow underneath it, not from the
# border shouting - a multi-stop gradient round every window reads as busy once
# it is on screen all day rather than in a screenshot.
rail="rgba(${accent}ee)"
bordersize=2
dim=0.25
glow=33      # alpha on the accent-tinted bloom under the focused window
unlit=88     # alpha on the flat black shadow under everything else

case "$name" in
    noir) ;;                       # the defaults are noir's
    felt)
        dim=0.22 ;;                # green is already dark; a full 0.25 buries it
    vegas)
        # The one table that keeps the gradient. Vegas is the strip at midnight
        # and is supposed to be loud, so it gets the full rail - pink, through
        # cyan bulbs, through the warm marquee orange and back - on a thicker
        # border, and the borderangle sweep on open actually has something to
        # move. Everywhere else that animation is a no-op, which is fine.
        rail="rgba(${accent}ee) rgba(2ee5ffee) rgba(${urgent}ee) rgba(${accent}ee) 115deg"
        bordersize=3
        dim=0.28 ;;
    daylight)
        dim=0.08                   # a light table. more than this and unfocused windows go grey, not dim
        glow=4d                    # gold on cream needs more of itself to show at all
        unlit=40 ;;                # and a full-strength black drop shadow looks like a bruise
esac

cat > "$config/hypr/colors.conf" <<EOF
# AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh — do not edit by hand.
# Rewritten whenever a table is chosen in the house bar's picker; sourced from
# hyprland.conf so the choice sticks across a restart. The \$-variables are here
# for reuse (e.g. from binds or window rules); the keywords below are what paint.

\$surface = rgb($surface)
\$text    = rgb($text)
\$subtext = rgb($subtext)
\$accent  = rgb($accent)
\$idle    = rgb($idle)
\$urgent  = rgb($urgent)

# The rail. Flat accent on every table but vegas, which keeps the gradient.
general:border_size = $bordersize
general:col.active_border = $rail
general:col.inactive_border = rgba(${idle}55)

# The spotlight.
decoration:dim_strength = $dim
decoration:shadow:color = rgba(${accent}${glow})
decoration:shadow:color_inactive = rgba(000000${unlit})
EOF

# --- hyprlock -----------------------------------------------------------------
# hyprlock.conf is static structure sourcing these $-variables, so the lock
# screen wears the active table. hyprlock reads its config each time it starts,
# so the next lock is already on the new table. Decimal rgba(), matching the
# format the shipped config used - dec() is up with the other colour helpers.

cat > "$config/hypr/lock-colours.conf" <<EOF
# AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh — do not edit by
# hand. The active table's palette, sourced from hyprlock.conf.

\$lockBackground = rgba($(dec "$surface"), 1.0)
\$lockOuter = rgba($(dec "$accent"), 0.55)
\$lockInner = rgba($(dec "$idle"), 0.75)
\$lockFont = rgba($(dec "$text"), 1.0)
\$lockCaps = rgba($(dec "$urgent"), 1.0)
\$lockClock = rgba($(dec "$accent"), 1.0)
\$lockSuits = rgba($(dec "$subtext"), 1.0)
\$lockPlaceholder = <span foreground="##$subtext">place your bets</span>
EOF

# --- Wallpaper ----------------------------------------------------------------
# One generated wallpaper per table, shipped in the repo. awww is the daemon the
# hypr config autostarts; fall back to swww for setups that use that instead.

wall="$repo/wallpapers/$name.png"
if [ -f "$wall" ]; then
    if command -v awww >/dev/null 2>&1; then
        awww img "$wall" >/dev/null 2>&1 || true
    elif command -v swww >/dev/null 2>&1; then
        swww img "$wall" >/dev/null 2>&1 || true
    fi
fi

# --- kitty --------------------------------------------------------------------
# The 16-colour deck can't be derived from six roles, so each table ships a
# pre-baked palette. kitty.conf includes current-table.conf; SIGUSR1 makes every
# running kitty re-read its config, so open terminals retint immediately.

if [ -f "$tables/kitty-$name.conf" ]; then
    cp "$tables/kitty-$name.conf" "$config/kitty/current-table.conf"
    pkill -USR1 -x kitty 2>/dev/null || true
fi

# --- rofi ---------------------------------------------------------------------
# house.rasi imports table-colours.rasi for its palette; everything rofi needs
# fits in the six roles, so generate it. rofi starts fresh per launch, so the
# next Super+D is already on the new table.

cat > "$config/rofi/themes/table-colours.rasi" <<EOF
/* AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh — do not edit.
 * The active table's palette, imported by house.rasi. */
* {
    surface:                 #${surface}E6;
    lacquer:                 #${idle};
    gold:                    #${accent};
    ivory:                   #${text};
    smoke:                   #${subtext};
    crimson:                 #${urgent};
    onaccent:                #${surface};
}
EOF

# --- btop ---------------------------------------------------------------------
# One pre-baked .theme per table (they ship in the btop stow package). Running
# btop instances pick it up on restart.

if [ -f "$config/btop/themes/house-$name.theme" ]; then
    sed -i "s/^color_theme = .*/color_theme = \"house-$name\"/" "$config/btop/btop.conf" 2>/dev/null || true
fi

# --- GTK ----------------------------------------------------------------------
# gtk-3.0/gtk.css and gtk-4.0/gtk.css are static structure referencing named
# colours; the palettes below are generated from the six roles. GTK apps read
# CSS once at startup, so open windows keep the old table until relaunched
# (thunar daemonises - `thunar -q` makes the next window pick it up).

window=$(mix "$surface" "$idle" 0.20)
raised=$(mix "$surface" "$idle" 0.40)
sunken=$(mix "$surface" "000000" 0.15)
hover=$(mix "$idle" "$text" 0.10)
active=$(mix "$idle" "$accent" 0.35)
bright=$(mix "$text" "ffffff" 0.30)
borderdim=$(mix "$surface" "$idle" 0.50)
disabled=$(mix "$subtext" "$surface" 0.35)

roles="/* AUTOGENERATED by cloon/newdot/house scripts/apply-theme.sh — do not edit.
 * The active table's palette, imported by gtk.css. */

@define-color house_surface #$surface;
@define-color house_window #$window;
@define-color house_raised #$raised;
@define-color house_sunken #$sunken;
@define-color house_text #$text;
@define-color house_subtext #$subtext;
@define-color house_accent #$accent;
@define-color house_onaccent #$surface;
@define-color house_idle #$idle;
@define-color house_hover #$hover;
@define-color house_active #$active;
@define-color house_bright #$bright;
@define-color house_border_dim #$borderdim;
@define-color house_disabled #$disabled;
@define-color house_urgent #$urgent;"

printf '%s\n' "$roles" > "$config/gtk-3.0/table-colours.css"

cat > "$config/gtk-4.0/table-colours.css" <<EOF
$roles

/* libadwaita's own names, same values. */
@define-color window_bg_color #$window;
@define-color window_fg_color #$text;
@define-color view_bg_color #$surface;
@define-color view_fg_color #$text;
@define-color headerbar_bg_color #$surface;
@define-color headerbar_fg_color #$text;
@define-color headerbar_border_color #$idle;
@define-color headerbar_backdrop_color #$sunken;
@define-color card_bg_color #$raised;
@define-color card_fg_color #$text;
@define-color popover_bg_color #$raised;
@define-color popover_fg_color #$text;
@define-color dialog_bg_color #$window;
@define-color dialog_fg_color #$text;
@define-color sidebar_bg_color #$sunken;
@define-color sidebar_fg_color #$text;
@define-color sidebar_backdrop_color #$surface;
@define-color accent_bg_color #$accent;
@define-color accent_fg_color #$surface;
@define-color accent_color #$accent;
@define-color destructive_bg_color #$urgent;
@define-color destructive_fg_color #$text;
@define-color destructive_color #$urgent;
@define-color error_bg_color #$urgent;
@define-color error_fg_color #$text;
@define-color error_color #$urgent;
@define-color warning_bg_color #$accent;
@define-color warning_fg_color #$surface;
@define-color warning_color #$accent;
EOF

# --- folder icons -------------------------------------------------------------
# One House-<Table> icon theme per table (gold, brass, neon pink, old gold
# folders over stock Adwaita). GTK on Wayland takes the icon theme from
# gsettings, and running GTK apps re-resolve icons live when it changes.

icons="House-$(printf '%s' "$name" | awk '{ print toupper(substr($0,1,1)) substr($0,2) }')"
if [ -d "$HOME/.local/share/icons/$icons" ] && command -v gsettings >/dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface icon-theme "$icons" 2>/dev/null || true
fi

# --- starship -----------------------------------------------------------------
# Same story as kitty: segment palettes are pre-baked per table. starship
# re-reads its config every prompt, so the very next Enter is on the new table.

if [ -f "$tables/starship-$name.toml" ]; then
    cp "$tables/starship-$name.toml" "$config/starship.toml"
fi

# --- Hyprland, live -----------------------------------------------------------
# `keyword` alone updates the stored value but doesn't redraw borders already on
# screen until the window is refocused - so a theme switch wouldn't visibly land.
# A reload re-sources hyprland.conf (hence colors.conf, just written above) and
# repaints every border; it does not re-run exec-once, so it's cheap and safe.
if command -v hyprctl >/dev/null 2>&1 && hyprctl version >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
fi
